# Generated by Django 2.2.7 on 2019-11-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartasEmJogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_partida', models.IntegerField(max_length=50)),
                ('ID_carta', models.IntegerField(max_length=10)),
                ('Posicao', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jogada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_partida', models.IntegerField(max_length=50)),
                ('ID_jogada', models.IntegerField(max_length=50)),
                ('ID_jogador', models.IntegerField(max_length=10)),
                ('Posicao_Carta', models.IntegerField(max_length=10)),
                ('Numero_da_jogada', models.IntegerField(max_length=10)),
                ('Turno_da_jogada', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_partida', models.IntegerField(max_length=50)),
                ('ID_Jogador1', models.TextField(max_length=20)),
                ('ID_Jogador2', models.TextField(max_length=20)),
                ('Status_partida', models.IntegerField(max_length=2)),
            ],
        ),
    ]
