# Generated by Django 2.2.7 on 2019-11-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogada',
            name='Numero_da_jogada',
        ),
    ]
