# Generated by Django 2.2.7 on 2019-11-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_jogada_numero_da_jogada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartasemjogo',
            name='ID_carta',
        ),
        migrations.RemoveField(
            model_name='cartasemjogo',
            name='ID_partida',
        ),
        migrations.RemoveField(
            model_name='cartasemjogo',
            name='Posicao',
        ),
        migrations.RemoveField(
            model_name='jogada',
            name='ID_jogada',
        ),
        migrations.RemoveField(
            model_name='jogada',
            name='ID_jogador',
        ),
        migrations.RemoveField(
            model_name='jogada',
            name='ID_partida',
        ),
        migrations.RemoveField(
            model_name='jogada',
            name='Posicao_Carta',
        ),
        migrations.RemoveField(
            model_name='jogada',
            name='Turno_da_jogada',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='ID_partida',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='Status_partida',
        ),
    ]
