# Generated by Django 2.2.6 on 2019-10-10 01:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleCarta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_verso', models.CharField(max_length=50)),
                ('anexo_frente', models.CharField(max_length=50)),
                ('nome_carta', models.CharField(max_length=20)),
                ('desc_carta', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Carta',
                'verbose_name_plural': 'Cartas',
            },
        ),
        migrations.CreateModel(
            name='ControlePartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.TimeField()),
                ('score_player1', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(4))),
                ('score_player2', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(4))),
                ('vencedor', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(4))),
                ('tipo_partida', models.CharField(choices=[('F', 'Fatec'), ('C', 'Casual'), ('R', 'Rankeado')], max_length=1)),
                ('dt_partida', models.DateTimeField(auto_now_add=True)),
                ('level_partida', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(4))),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_jogadas_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_jogadas_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controle Partida',
                'verbose_name_plural': 'Controle Partidas',
            },
        ),
    ]
