# Generated by Django 2.2.6 on 2019-11-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogodamemoria', '0002_auto_20191115_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlepartida',
            name='estado',
            field=models.CharField(choices=[('A', 'Aberta'), ('E', 'Em andamento'), ('N', 'Finalizada')], default='A', max_length=1),
        ),
    ]
