# Generated by Django 2.2.6 on 2019-11-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogodamemoria', '0003_controlepartida_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlepartida',
            name='nome_partida',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
