# Generated by Django 2.2.6 on 2019-11-15 20:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogodamemoria', '0004_controlepartida_nome_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlepartida',
            name='duracao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlepartida',
            name='level_partida',
            field=models.CharField(choices=[('I', 'Fácil'), ('O', 'Normal'), ('D', 'Difícil'), ('F', 'Fatec')], max_length=1),
        ),
        migrations.AlterField(
            model_name='controlepartida',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidas_jogadas_as_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controlepartida',
            name='score_player1',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(4)),
        ),
        migrations.AlterField(
            model_name='controlepartida',
            name='score_player2',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(4)),
        ),
        migrations.AlterField(
            model_name='controlepartida',
            name='tipo_partida',
            field=models.CharField(choices=[('C', 'Casual'), ('R', 'Rankeado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='controlepartida',
            name='vencedor',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(4)),
        ),
    ]
