# Generated by Django 2.2.6 on 2019-11-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogodamemoria', '0005_auto_20191115_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlepartida',
            name='player1_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlepartida',
            name='player2_ok',
            field=models.BooleanField(default=False),
        ),
    ]
