# Generated by Django 2.2.6 on 2019-11-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_cadastrais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='user_images/'),
        ),
    ]
